### ISSUE TITLE
how does gole work?

### ISSUE THREAD

**Issue by kt5ttk99** [shawwwn/gole#5]
I try to drill a hole as follows
./gole -v tcp 0.0.0.0:3333 112.49.232.96:4444 -op server -fwd=127.0.0.1:8080
./gole -v tcp 0.0.0.0:4444 223.104.51.140:4444 -op client -fwd=127.0.0.1:1111
But it seems unlikely to succeed：
<img width="404" alt="1705046125565" src="https://github.com/shawwwn/Gole/assets/71433345/804af933-73d3-488b-b946-ead59e2b5aa9">
What should I do？

**Comment by shawwwn** [comment]
If both sides are on symmetric NATs, then the operation is unlikely to succeed.

**Comment by 204504bySE** [comment]
Same here, hole punching doesn't work in TCP. It only works in UDP. It's not only in this app but every NAT.
So TCP tunneling actually requires something like TCP over UDP.
