### ISSUE TITLE
ovpn?

### ISSUE THREAD

**Issue by freecode505** [shawwwn/gole#6]
Can this work with openvpn?

**Comment by shawwwn** [comment]
It should work, in theory.

**Comment by MCjorsh5** [comment]
How can I not understand some parts more than the entire server?

Client:

./gole-linux-amd64 -enc xor -key "your_encryption_key" tcp 127.0.0.1:9998 193.31.30.148:8088 -fwd  -proto tcp

* 127.0.0.1 9998 OVPN LISTENING LOCAL
* 193.31.30.148:9999 Listening real ovpn

Server:

 ./gole-linux-amd64 -enc xor -key "your_encryption_key" tcp 193.31.30.148:8088 193.31.30.148:9999 -fwd 193.31.30.148:9999

Gole v1.2
tunnel mode: TCP
operation: holepunch
====================
punching holes: [local]193.31.30.148:8088 ---> [remote]193.31.30.148:9999
recv() failed. EOF
Failed to punch hole. EOF


193.31.30.148:9999 Is ovpn running as it should be?

**Comment by shawwwn** [comment]
I see your parameters are all messed up. Do you want to run Gole locally because I see only one public IP(193.31.30.148) in your configuration. You need two IPs to make it work.

**Comment by MCjorsh5** [comment]
I want to run this server publicly to bypass firewall

**Comment by shawwwn** [comment]
Then you need two machine and two public IPs.
One is inside the firewall where you run Gole in client mode, the other is outside the firewall where you run Gole in server mode.  
You cant run both modes in one machine.

**Comment by MCjorsh5** [comment]
This is what I'm doing, don't tell me that the server has to put my client's IP, the IP that expects to be accepted by the server? Otherwise it wouldn't work.

**Comment by shawwwn** [comment]
I'm sorry I really don't understand your request.
